cat ../testcase/1.in | ./main.elf > 1.ans
cat ../testcase/2.in | ./main.elf > 2.ans
cat ../testcase/3.in | ./main.elf > 3.ans
cat ../testcase/4.in | ./main.elf > 4.ans
cat ../testcase/5.in | ./main.elf > 5.ans
cat ../testcase/6.in | ./main.elf > 6.ans
cat ../testcase/7.in | ./main.elf > 7.ans
cat ../testcase/8.in | ./main.elf > 8.ans
cat ../testcase/9.in | ./main.elf > 9.ans
cat ../testcase/10.in | ./main.elf > 10.ans
